Update whats.py
Ankit404butfound/PyWhatKit pull request #170
Opened 2022-01-09 19:25 UTC by Sachit71

A bug probably, but here's the issue the
 `pywhatkit.sendwhatmsg_to_group_instantly("AB123CDEFGHijklmn", "Hey All!")`
 but when running the script I keep getting this
` error message in sendwhatmsg_to_group_instantly time.sleep(sleep_time) NameError: name 'sleep_time' is not defined`

So I checked the code and found this: 
![image](https://user-images.githubusercontent.com/72592470/148697501-2e6e5585-1956-4a93-81d7-d858e0453e9c.png)

the variable sleep_time is not defined in line 128, so I set it to 4, why 4? because like the send whatsapp message instantly the sleep_time was set to 4, so I decided to set it to 4, please do check and lemme know if anything's wrong.

2022-01-09 19:31 UTC, Sachit71 commented
How does one deal with the lint error 😭

2022-01-10 03:25 UTC, Naman23-coder requested changes
```py
def sendwhatmsg_to_group_instantly(
    group_id: str,
    message: str,
    wait_time: int = 15,
    tab_close: bool = False,
    close_time: int = 3,
) -> None:
    """Send WhatsApp Message to a Group Instantly"""

    current_time = time.localtime()

    time.sleep(4)
    core.send_message(message=message, receiver=group_id, wait_time=wait_time)
    log.log_message(_time=current_time, receiver=group_id, message=message)
    if tab_close:
        core.close_tab(wait_time=close_time)```

2022-01-10 04:16 UTC, Sachit71 commented
@Naman23-coder again the sleep_time variable is not defined here, hence I added the 4, I suggest you remove the 
`time.sleep(sleep_time)` line before submitting.

2022-01-11 18:46 UTC, aaryanrr commented
Hey @Sachit71, thanks for the valuable contribution. The lint is still failing. You need to run `pre-commit run --all-files` before pushing changes.

2022-01-12 07:25 UTC, Sachit71 commented
Hi aryan, I'm using the web version of GitHub and have no idea as to how to deal with this problem.

2022-01-12 07:39 UTC, Naman23-coder commented
hey @Sachit71 i can resolve this problem on discord dm

2022-01-12 12:12 UTC, Sachit71 commented
Woohoo let's go, no errors

2022-01-15 11:40 UTC, merged

2022-01-15 11:41 UTC, aaryanrr commented
Merged :)